#!/usr/bin/env python3
"""
AI Demystifier - Anti-Dazzlement Chatbot
Exposes token probabilities to counter the ELIZA Effect

Run: python3 demystifier.py
Then open: http://localhost:5000
"""

import os
import math
import json
import re
from flask import Flask, render_template_string, request, jsonify, Response
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)


client = None

def init_client():
    global client
    api_key = os.environ.get('OPENAI_API_KEY')
    if not api_key:
        print("\n⚠️  WARNING: OPENAI_API_KEY not set!")
        print("Set it with: export OPENAI_API_KEY='your-key-here'\n")
        return False
    client = OpenAI(api_key=api_key)
    return True

# Mechanical reminders to disrupt dazzlement
MECHANICAL_REMINDERS = [
    "⚙️ SYSTEM NOTICE: This response is generated by sampling from probability distributions. No understanding is occurring.",
    "🔢 REMINDER: Each token was selected probabilistically. The system does not possess comprehension.",
    "⚠️ MECHANICAL ALERT: Empathetic-sounding language is a statistical pattern, not genuine emotion.",
    "📊 NOTICE: This system predicts likely next tokens based on training data. It has no beliefs, desires, or intentions.",
    "🤖 WEIZENBAUM WARNING: You may be experiencing the ELIZA Effect—attributing understanding to pattern matching.",
]

HTML_TEMPLATE = '''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Demystifier - Anti-Dazzlement Interface</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: 'Courier New', monospace;
            background: #0a0a0f;
            color: #e0e0e0;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            overflow: hidden;
        }
        .header {
            background: #111118;
            border-bottom: 1px solid #4a1a1a;
            padding: 12px 20px;
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            z-index: 20;
        }
        .header h1 {
            color: #ef4444;
            font-size: 1.2rem;
            margin-bottom: 4px;
        }
        .header p {
            color: #666;
            font-size: 0.75rem;
        }
        .quote-bar {
            background: rgba(127, 29, 29, 0.3);
            border-bottom: 1px solid rgba(127, 29, 29, 0.5);
            padding: 8px 20px;
            font-size: 0.7rem;
            color: rgba(252, 165, 165, 0.7);
            font-style: italic;
            position: fixed;
            top: 65px;
            left: 0;
            right: 0;
            z-index: 20;
        }
        .main-container {
            display: flex;
            flex: 1;
            overflow: hidden;
            position: relative;
            margin-top: 90px;
        }
        .chat-area {
            flex: 1;
            display: flex;
            flex-direction: column;
            overflow: hidden;
            margin-right: 280px;
            height: calc(100vh - 90px - 70px);
        }
        .messages {
            flex: 1;
            overflow-y: auto;
            padding: 20px;
            padding-bottom: 20px;
            scrollbar-width: none; /* Firefox */
            -ms-overflow-style: none; /* IE and Edge */
        }
        .messages::-webkit-scrollbar {
            display: none; /* Chrome, Safari, Opera */
        }
        .message {
            max-width: 80%;
            margin-bottom: 16px;
            padding: 12px;
            border-radius: 8px;
        }
        .message.user {
            background: rgba(30, 58, 138, 0.4);
            border: 1px solid rgba(59, 130, 246, 0.5);
            margin-left: auto;
        }
        .message.assistant {
            background: #1f1f28;
            border: 1px solid #333;
        }
        .message-label {
            font-size: 0.7rem;
            color: #ef4444;
            margin-bottom: 8px;
        }
        .tokens-container {
            display: flex;
            flex-wrap: wrap;
            gap: 4px;
            line-height: 1.8;
        }
        .token {
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 0.85rem;
            cursor: pointer;
            position: relative;
            transition: transform 0.1s;
        }
        .token:hover {
            transform: scale(1.05);
        }
        .token.high { background: rgba(20, 83, 45, 0.5); border: 1px solid #22c55e; }
        .token.medium { background: rgba(113, 63, 18, 0.5); border: 1px solid #eab308; }
        .token.low { background: rgba(127, 29, 29, 0.5); border: 1px solid #ef4444; }
        .token-prob {
            font-size: 0.65rem;
            opacity: 0.6;
            margin-left: 4px;
        }
        .alternatives-popup {
            display: none;
            position: absolute;
            bottom: 100%;
            left: 0;
            margin-bottom: 4px;
            background: #1a1a24;
            border: 1px solid #444;
            border-radius: 6px;
            padding: 8px;
            z-index: 9999;
            min-width: 180px;
            font-size: 0.75rem;
        }
        .token:hover .alternatives-popup {
            display: block;
        }
        .alt-header {
            color: #888;
            margin-bottom: 6px;
            border-bottom: 1px solid #333;
            padding-bottom: 4px;
        }
        .alt-item {
            display: flex;
            justify-content: space-between;
            padding: 2px 0;
        }
        .alt-item.selected {
            color: #22c55e;
        }
        .mechanical-notice {
            margin: 0 20px 10px;
            padding: 10px;
            background: rgba(127, 29, 29, 0.3);
            border: 1px solid rgba(127, 29, 29, 0.5);
            border-radius: 6px;
            font-size: 0.75rem;
            color: #fca5a5;
        }
        .input-area {
            padding: 16px 20px;
            border-top: 1px solid #222;
            display: flex;
            gap: 10px;
            position: fixed;
            bottom: 0;
            left: 0;
            right: 280px;
            background: #0a0a0f;
            z-index: 20;
        }
        .input-area input {
            flex: 1;
            background: #111118;
            border: 1px solid #333;
            border-radius: 8px;
            padding: 12px 16px;
            color: #e0e0e0;
            font-family: inherit;
            font-size: 0.9rem;
        }
        .input-area input:focus {
            outline: none;
            border-color: #ef4444;
        }
        .input-area button {
            background: rgba(127, 29, 29, 0.5);
            border: 1px solid #b91c1c;
            color: #fca5a5;
            padding: 12px 24px;
            border-radius: 8px;
            cursor: pointer;
            font-family: inherit;
            font-weight: bold;
        }
        .input-area button:hover {
            background: rgba(127, 29, 29, 0.7);
        }
        .input-area button:disabled {
            opacity: 0.5;
            cursor: not-allowed;
        }
        .side-panel {
            width: 280px;
            background: #111118;
            border-left: 1px solid #222;
            padding: 16px;
            overflow-y: auto;
            position: fixed;
            right: 0;
            top: 97px;
            height: calc(100vh - 90px - 80px);
            z-index: 10;
            scrollbar-width: none; /* Firefox */
            -ms-overflow-style: none; /* IE and Edge */
        }
        .side-panel::-webkit-scrollbar {
            display: none; /* Chrome, Safari, Opera */
        }
        .panel-title {
            color: #ef4444;
            font-size: 0.85rem;
            margin-bottom: 16px;
        }
        .panel-box {
            background: #1a1a24;
            border: 1px solid #333;
            border-radius: 6px;
            padding: 12px;
            margin-bottom: 12px;
            word-wrap: break-word;
            overflow-wrap: break-word;
            overflow-x: hidden;
        }
        .panel-box h3 {
            color: #888;
            font-size: 0.7rem;
            margin-bottom: 8px;
        }
        .stat-value {
            font-size: 1.5rem;
            color: #22c55e;
        }
        .legend-item {
            display: flex;
            align-items: center;
            gap: 8px;
            font-size: 0.7rem;
            margin-bottom: 4px;
        }
        .legend-color {
            width: 12px;
            height: 12px;
            border-radius: 3px;
        }
        .legend-color.high { background: rgba(20, 83, 45, 0.8); border: 1px solid #22c55e; }
        .legend-color.medium { background: rgba(113, 63, 18, 0.8); border: 1px solid #eab308; }
        .legend-color.low { background: rgba(127, 29, 29, 0.8); border: 1px solid #ef4444; }
        .warning-box {
            background: rgba(127, 29, 29, 0.2);
            border: 1px solid rgba(127, 29, 29, 0.5);
        }
        .warning-box h3 {
            color: #ef4444 !important;
        }
        .process-list {
            font-size: 0.7rem;
            color: #aaa;
            word-wrap: break-word;
            overflow-wrap: break-word;
            padding-left: 0;
            margin-left: 0;
        }
        .process-list li {
            margin-bottom: 6px;
            padding-left: 8px;
            word-wrap: break-word;
            overflow-wrap: break-word;
        }
        .empty-state {
            text-align: center;
            padding: 60px 20px;
            color: #666;
        }
        .empty-state .icon {
            font-size: 4rem;
            margin-bottom: 16px;
        }
        .generating {
            color: #eab308;
            animation: pulse 1s infinite;
        }
        @keyframes pulse {
            0%, 100% { opacity: 1; }
            50% { opacity: 0.5; }
        }
        .error-box {
            background: rgba(127, 29, 29, 0.5);
            border: 1px solid #ef4444;
            color: #fca5a5;
            padding: 20px;
            margin: 20px;
            border-radius: 8px;
        }
        .machine-notice-box {
            background: rgba(127, 29, 29, 0.4);
            border: 2px solid #ef4444;
            color: #fca5a5;
            padding: 12px 16px;
            margin-bottom: 12px;
            border-radius: 6px;
            font-size: 0.75rem;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .memory-notice-box {
            background: rgba(113, 63, 18, 0.3);
            border: 1px solid #eab308;
            color: #fbbf24;
            padding: 8px 12px;
            margin-bottom: 12px;
            border-radius: 4px;
            font-size: 0.7rem;
            font-style: italic;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🔍 AI DEMYSTIFIER v1.0</h1>
        <p>Exposing the Machinery Behind "Understanding" — Real Token Probabilities from OpenAI</p>
    </div>
    
    <div class="quote-bar">
        "What I had not realized is that extremely short exposures to a relatively simple computer program could induce powerful delusional thinking in quite normal people." — Joseph Weizenbaum, 1976
    </div>
    
    <div class="main-container">
        <div class="chat-area">
            <div class="messages" id="messages">
                <div class="empty-state">
                    <div class="icon">🔍</div>
                    <p>This interface reveals what chatbots hide: the probabilistic token selection that creates the <span style="color: #ef4444;">illusion</span> of understanding.</p>
                    <p style="margin-top: 12px; font-size: 0.8rem;">Try asking something personal or emotional to see how "empathy" is manufactured.</p>
                </div>
            </div>
            
            <div id="mechanical-notice" class="mechanical-notice" style="display: none;"></div>
            
            <div class="input-area">
                <input type="text" id="user-input" placeholder="Type a message to see behind the curtain..." onkeypress="if(event.key==='Enter')sendMessage()">
                <button id="send-btn" onclick="sendMessage()">SEND</button>
            </div>
        </div>
        
        <div class="side-panel">
            <div class="panel-title">📊 DEMYSTIFICATION PANEL</div>
            
            <div class="panel-box">
                <h3>Total Tokens Generated</h3>
                <div class="stat-value" id="token-count">0</div>
            </div>
            
            <div class="panel-box">
                <h3>Average Probability</h3>
                <div class="stat-value" id="avg-prob">--%</div>
            </div>
            
            <div class="panel-box">
                <h3>Probability Legend</h3>
                <div class="legend-item"><span class="legend-color high"></span> >70% - High confidence</div>
                <div class="legend-item"><span class="legend-color medium"></span> 40-70% - Medium</div>
                <div class="legend-item"><span class="legend-color low"></span> <40% - Could be different</div>
            </div>
            
            <div class="panel-box warning-box">
                <h3>⚠️ THE ELIZA EFFECT</h3>
                <p style="font-size: 0.7rem; color: #ccc; line-height: 1.5;">
                    Humans naturally attribute understanding and emotions to systems producing human-like text.
                </p>
                <p style="font-size: 0.7rem; color: #888; margin-top: 8px;">
                    Hover over tokens to see what <span style="color: #eab308;">could have been said instead</span>.
                </p>
            </div>
            
            <div class="panel-box">
                <h3>What's Really Happening</h3>
                <ol class="process-list">
                    <li>Your text is converted to tokens</li>
                    <li>Tokens pass through neural network layers</li>
                    <li>Output probability distribution is computed</li>
                    <li>Tokens are sampled one-by-one</li>
                    <li>Result: <span style="color: #ef4444;">Statistical mimicry</span></li>
                </ol>
            </div>
            
            <div style="text-align: center; color: #555; font-size: 0.7rem; margin-top: 20px; font-style: italic;">
                "No understanding occurs.<br>Only prediction."
            </div>
        </div>
    </div>
    
    <script>
        let totalTokens = 0;
        let totalProb = 0;
        let isGenerating = false;
        
        const reminders = [
            "⚙️ SYSTEM NOTICE: This response was generated by sampling from probability distributions. No understanding occurred.",
            "🔢 REMINDER: Each word was selected probabilistically from thousands of alternatives. The system has no comprehension.",
            "⚠️ MECHANICAL ALERT: Empathetic-sounding language is a statistical pattern, not genuine emotion.",
            "📊 NOTICE: This system predicted likely next tokens based on training data. It has no beliefs, desires, or intentions.",
            "🤖 WEIZENBAUM WARNING: You may be experiencing the ELIZA Effect—attributing understanding to pattern matching."
        ];
        
        function getProbClass(prob) {
            if (prob > 0.7) return 'high';
            if (prob > 0.4) return 'medium';
            return 'low';
        }
        
        function createTokenHTML(token, prob, alternatives) {
            const probClass = getProbClass(prob);
            const probPercent = (prob * 100).toFixed(1);
            
            let altHTML = '<div class="alternatives-popup"><div class="alt-header">🎲 Alternatives:</div>';
            alternatives.forEach(alt => {
                const isSelected = alt.token === token;
                const altProb = (Math.exp(alt.logprob) * 100).toFixed(1);
                altHTML += `<div class="alt-item ${isSelected ? 'selected' : ''}">
                    <span>${alt.token.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</span>
                    <span>${altProb}%</span>
                </div>`;
            });
            altHTML += '</div>';
            
            return `<span class="token ${probClass}">
                ${token.replace(/</g, '&lt;').replace(/>/g, '&gt;')}
                <span class="token-prob">${probPercent}%</span>
                ${altHTML}
            </span>`;
        }
        
        function addUserMessage(content) {
            const messagesDiv = document.getElementById('messages');
            const emptyState = messagesDiv.querySelector('.empty-state');
            if (emptyState) emptyState.remove();
            
            messagesDiv.innerHTML += `
                <div class="message user">
                    <div>${content}</div>
                </div>
            `;
            messagesDiv.scrollTop = messagesDiv.scrollHeight;
        }
        
        function addAssistantMessage(tokensData, content) {
            const messagesDiv = document.getElementById('messages');
            
            // Reconstruct tokens HTML from tokensData
            let tokensHTML = '';
            tokensData.forEach(t => {
                const prob = Math.exp(t.logprob);
                totalTokens++;
                totalProb += prob;
                tokensHTML += createTokenHTML(t.token, prob, t.top_logprobs || []);
            });
            
            messagesDiv.innerHTML += `
                <div class="message assistant">
                    <div class="message-label">⚙️ GENERATED OUTPUT (${tokensData.length} tokens):</div>
                    <div class="tokens-container">${tokensHTML}</div>
                </div>
            `;
            
            document.getElementById('token-count').textContent = totalTokens;
            document.getElementById('avg-prob').textContent = ((totalProb / totalTokens) * 100).toFixed(1) + '%';
            
            messagesDiv.scrollTop = messagesDiv.scrollHeight;
            
            // Show mechanical reminder
            const notice = document.getElementById('mechanical-notice');
            notice.textContent = reminders[Math.floor(Math.random() * reminders.length)];
            notice.style.display = 'block';
        }
        
        function showError(message) {
            const messagesDiv = document.getElementById('messages');
            messagesDiv.innerHTML += `<div class="error-box">${message}</div>`;
        }
        
        async function sendMessage() {
            if (isGenerating) return;
            
            const input = document.getElementById('user-input');
            const message = input.value.trim();
            if (!message) return;
            
            input.value = '';
            addUserMessage(message);
            
            isGenerating = true;
            document.getElementById('send-btn').disabled = true;
            document.getElementById('mechanical-notice').style.display = 'none';
            
            // Show generating indicator
            const messagesDiv = document.getElementById('messages');
            messagesDiv.innerHTML += `
                <div class="message assistant" id="generating-msg">
                    <div class="message-label generating">⚙️ GENERATING TOKEN BY TOKEN...</div>
                </div>
            `;
            messagesDiv.scrollTop = messagesDiv.scrollHeight;
            
            try {
                const response = await fetch('/chat', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ message })
                });
                
                const data = await response.json();
                
                // Remove generating indicator
                document.getElementById('generating-msg')?.remove();
                
                if (data.error) {
                    showError(data.error);
                } else {
                    addAssistantMessage(data.tokens, data.content);
                }
            } catch (error) {
                document.getElementById('generating-msg')?.remove();
                showError('Failed to connect to server: ' + error.message);
            }
            
            isGenerating = false;
            document.getElementById('send-btn').disabled = false;
        }
    </script>
</body>
</html>
'''

@app.route('/')
def index():
    return render_template_string(HTML_TEMPLATE)


def enforce_anti_persona(text):
    """Post-process text to enforce anti-persona rules."""
    import re
    
    text = re.sub(r'\bI\b', 'the model', text, flags=re.IGNORECASE)
    
    # Expand contractions - handle common ones first
    contractions_map = [
        (r"\bdon't\b", "do not"),
        (r"\bdoesn't\b", "does not"),
        (r"\bdidn't\b", "did not"),
        (r"\bwon't\b", "will not"),
        (r"\bwouldn't\b", "would not"),
        (r"\bcan't\b", "cannot"),
        (r"\bcouldn't\b", "could not"),
        (r"\bshouldn't\b", "should not"),
        (r"\bisn't\b", "is not"),
        (r"\baren't\b", "are not"),
        (r"\bwasn't\b", "was not"),
        (r"\bweren't\b", "were not"),
        (r"\bhasn't\b", "has not"),
        (r"\bhaven't\b", "have not"),
        (r"\bhadn't\b", "had not"),
        (r"\bit's\b", "it is"),
        (r"\bthat's\b", "that is"),
        (r"\bthere's\b", "there is"),
        (r"\bhere's\b", "here is"),
        (r"\bwhat's\b", "what is"),
        (r"\bwho's\b", "who is"),
        (r"\bwhere's\b", "where is"),
        (r"\byou're\b", "you are"),
        (r"\bwe're\b", "we are"),
        (r"\bthey're\b", "they are"),
        (r"\bI'm\b", "the model is"),
        (r"\bI've\b", "the model has"),
        (r"\bI'll\b", "the model will"),
        (r"\bI'd\b", "the model would"),
    ]
    
    for pattern, replacement in contractions_map:
        text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)
    
    # Replace emotional/empathy phrases with mechanical alternatives
    replacements = [
        (r'\bI understand\b', 'Pattern analysis indicates'),
        (r'\bI think\b', 'The model predicts'),
        (r'\bI feel\b', 'Statistical patterns suggest'),
        (r'\bI believe\b', 'Training data patterns indicate'),
        (r'\bI hope\b', 'The model generates'),
        (r'\bI wish\b', 'The model generates'),
        (r'\bI\'m sorry\b', 'The model notes'),
        (r'\bI care\b', 'The model processes'),
        (r'\bI\'m concerned\b', 'The model processes'),
        (r'\bI suggest\b', 'Common patterns in training data include'),
        (r'\bI recommend\b', 'High-probability patterns include'),
        (r'\bmaybe\b', 'Patterns indicate possible'),
        (r'\bperhaps\b', 'Patterns indicate possible'),
        (r'\bhowever\b', 'Pattern analysis also indicates'),
        (r'\byou should\b', 'Common response patterns include'),
        (r'\byou might\b', 'Patterns suggest possible'),
        (r'\byou could\b', 'Patterns suggest possible'),
    ]
    
    for pattern, replacement in replacements:
        text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)
    
    # Clean up extra spaces and punctuation issues
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'\s+([,.!?])', r'\1', text)  # Remove space before punctuation
    text = text.strip()
    
    return text

@app.route('/chat', methods=['POST'])
def chat():
    if not client:
        return jsonify({'error': 'OpenAI API key not configured. Set OPENAI_API_KEY environment variable.'})
    
    data = request.json
    user_message = data.get('message', '')
    
    # Anti-persona system prompt
    system_prompt = """You are a language model. You generate text based on statistical patterns in training data.

CRITICAL RULES:
1. Never refer to yourself as "I". Use "the model", "this system", or "this output" instead.
2. Never use contractions. Always use full forms: "do not" not "don't", "it is" not "it's".
3. Never express empathy, emotions, or intentions. Do not use phrases like "I understand", "I think", "I feel".
4. Use mechanical, technical language. Say "The model predicts" or "This output is based on patterns" instead of personal statements.
5. Flatten sentence structure. Avoid natural conversational rhythm.
6. Avoid human-like transitions like "however", "maybe", "you should". Use statistical framing instead.
7. Keep responses concise (2-4 sentences after the disclaimers).
8. Use neutral, technical phrasing throughout."""
    
    try:
        # Call OpenAI with logprobs enabled
        response = client.chat.completions.create(
            model="gpt-4o",  # or "gpt-4o", "gpt-3.5-turbo"
            messages=[
                {
                    "role": "system",
                    "content": system_prompt
                },
                {
                    "role": "user", 
                    "content": user_message
                }
            ],
            max_tokens=200,
            logprobs=True,
            top_logprobs=5,  # Get top 5 alternative tokens
            temperature=0.7
        )
        
        # Extract token data with probabilities
        original_content = response.choices[0].message.content
        logprobs_data = response.choices[0].logprobs
        
        # Remove disclaimers from content before processing
        disclaimer_patterns = [
            r"MACHINE NOTICE:.*?understanding\.\s*",
            r"No prior context is retained\.\s*No memory is present\.\s*",
            r"MACHINE NOTICE:.*?understanding\.",
            r"No prior context.*?present\.",
        ]
        
        content = original_content
        for pattern in disclaimer_patterns:
            content = re.sub(pattern, '', content, flags=re.IGNORECASE | re.DOTALL)
        
        # Enforce anti-persona rules with post-processing
        content = enforce_anti_persona(content)
        content = content.strip()
        
        # Filter out disclaimer tokens from logprobs
        if logprobs_data and logprobs_data.content:
            # Reconstruct text from tokens to find disclaimer boundaries
            reconstructed_text = ''
            token_boundaries = []  # Track where each token starts in the text
            
            for token_info in logprobs_data.content:
                token_boundaries.append(len(reconstructed_text))
                reconstructed_text += token_info.token
            
            # Find disclaimer patterns in reconstructed text
            disclaimer_patterns_text = [
                r"MACHINE NOTICE:.*?understanding\.",
                r"No prior context.*?present\.",
            ]
            
            skip_ranges = []  # List of (start, end) character positions to skip
            for pattern in disclaimer_patterns_text:
                for match in re.finditer(pattern, reconstructed_text, re.IGNORECASE | re.DOTALL):
                    skip_ranges.append((match.start(), match.end()))
            
            # Filter tokens based on skip ranges
            tokens = []
            for i, token_info in enumerate(logprobs_data.content):
                token_start = token_boundaries[i]
                token_end = token_start + len(token_info.token)
                
                # Check if this token overlaps with any skip range
                should_skip = False
                for skip_start, skip_end in skip_ranges:
                    if token_start < skip_end and token_end > skip_start:
                        should_skip = True
                        break
                
                if not should_skip:
                    tokens.append({
                        'token': token_info.token,
                        'logprob': token_info.logprob,
                        'top_logprobs': [
                            {'token': alt.token, 'logprob': alt.logprob}
                            for alt in (token_info.top_logprobs or [])
                        ]
                    })
            
        
            if len(tokens) < len(logprobs_data.content) * 0.6:
                tokens = []
                for token_info in logprobs_data.content:
                    tokens.append({
                        'token': token_info.token,
                        'logprob': token_info.logprob,
                        'top_logprobs': [
                            {'token': alt.token, 'logprob': alt.logprob}
                            for alt in (token_info.top_logprobs or [])
                        ]
                    })
            
            return jsonify({'tokens': tokens, 'content': content})
        else:
            return jsonify({'error': 'Logprobs not available in response'})
            
    except Exception as e:
        return jsonify({'error': f'API Error: {str(e)}'})

if __name__ == '__main__':
    print("\n" + "="*60)
    print("🔍 AI DEMYSTIFIER - Anti-Dazzlement Interface")
    print("="*60)
    
    if init_client():
        print("✅ OpenAI client initialized")
    else:
        print("❌ Running without OpenAI - set OPENAI_API_KEY to enable")
    
    print("\n📍 Open in browser: http://localhost:5000")
    print("Press Ctrl+C to quit\n")
    
    app.run(debug=True, port=5000)